### ISSUE TITLE
@conda-forge-admin, please add user @dhirschfeld

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/azure-mgmt-subscription-feedstock#5]
### Additional comment:

Hi @conda-forge/azure-mgmt-subscription 👋 
I'd like to help out keeping this feedstock up-to-date.

**Comment by tim-werner** [comment]
dhirschfeld was added as maintainer

**Comment by dhirschfeld** [comment]
Thanks, strange that the not didn't open a PR.
